
```{r}
source('src/functions.R')
datasetpath <- 'Datasets/Diploid/Demo_Diploid_Single'
```

```{r}
imageset <- read_in_imageset(datasetpath)
channels <- read_in_channels(imageset[1,], datasetpath)
imggray <- convert_to_grayscale(channels)
# img <- scale_intensities(imggray)  #problem -- refs/grayscale
#cells <- detect_cells(imggray)
 cells <- detect_cells(imggray) 
```

```{r}

detect_membranes <-function(img)
{
  message("########################CELLS########################")
  
  cells_blurred = gblur(img[,,gfp_channel], sigma = 2)
  ct = thresh(cells_blurred, offset = 0.005)
  
  cm = bwlabel(ct)
  FS = computeFeatures.shape(cm)
  sel <- which(FS[,"s.area"] < 500)
  membranes <-rmObjects(cm, sel)


  FCM <- computeFeatures.moment(membranes)
  res <- remove_edge_membranes_temp(membranes, FCM, dim(img[,,cmac_channel]))



  
  message(paste0("Number of cells detected on first pass: ", length(table(membranes))))

  list(removed = res$removed, membranes = res$membranes, FMS = res$FMS)
  
}
```

```{r}
c <-detect_membranes(imggray)
```


```{r}
remove_edge_membranes_temp<-function(membranes, FMM, dim_img)
{
  
 
  
  contours <- ocontour(membranes)
  bound <- list(l = 3,
                r = dim_img[1]-3,
                t = 3,
                b = dim_img[2]-3)
  # find more efficient way to do this
  left <- lapply(contours, function(x){min(x[,1])})
  right <- lapply(contours, function(x){max(x[,1])})
  top <- lapply(contours, function(x){min(x[,2])})
  bottom <- lapply(contours, function(x){max(x[,2])})
  edge_cells <- c(which(left < bound$l),which(right > bound$r),  which(top < bound$t),which(bottom > bound$b))
  edge_cells <- as.numeric(names(edge_cells))
  edge_cells <- unique(edge_cells) #line might be unecessary

  removed_ind = which(!(seq(1, length(table(membranes))) %in% edge_cells))

  removed = rmObjects(membranes, removed_ind)
  
  membranes <- rmObjects(membranes, edge_cells)
  membranes <- bwlabel(membranes)
  FMS <- computeFeatures.shape(membranes)
  
  list(removed = removed, membranes = membranes, FMS = FMS)
  
}

```



```{r}
find_vacuoles_temp <- function(cell_info, img)
{
  message("######################VACUOLES#######################")
  
  b <- max(cell_info$FMS[,"s.radius.min"])
 
  vmask = thresh(img[,,cmac_channel],w=b,h=b,offset = sd(img[,,cmac_channel]))
  vmask = opening(vmask, makeBrush(5,shape="disc"))
  vmask = fillHull(vmask)
  vmask = bwlabel(vmask)

  message(paste0("Number of vacuoles detected on first pass: ", format(length(table(vmask)), nsmall = 4)))
  
 
  
  message(paste0("Number of vacuoles after segmask: ", length(table(vmask))))
  
  FV <- computeFeatures(vmask, ref= img[,,gfp_channel], xname = "vac")

  res<-list(vacuoles = vmask, 
       FV = FV)
  
 # res <- remove_empty_cells(cell_info, vmask, img)
  #message(paste0("Number of vacuoles after multiples removed: ", length(table(res$vacuoles))))
  return(res)

}
```

```{r}
vacs <- find_vacuoles_temp(c, imggray)
```

```{r}
newdf <- exclude_and_bind(c$membranes, vacs$vacuoles, df)
```


```{r}

p<-paintObjects(res$vacuoles,tgt = channels$gfp, col = c('red','red'))
pp <- paintObjects(cells$membranes, tgt = p, col = c('white', 'white'))
```

```{r}
 # some small computations to speed things up
  b <- 2*max(cell_info$FCCI[,"s.radius.max"])
  cand <- c(which(FMM[,"m.cx"] < b),
            which(FMM[,"m.cy"]))
  
  
```


```{r}
df <- data.frame(cellID = integer(),
                 vacuoles = list(),
                 cell_area = double(),
                 vac_area = double(),  #this will be a sum
                 PM_vac_ratio = double(),
                 cell_mpi = double(),
                 vac_mpi = double())
```


```{r}
remove_empty_cells <- function(cell_info, vmask, img)
{
  
  l = length(table(cell_info$cell_bodies))
  l = l-1
  
  empty_cells <- vector("list", l)
  
  for(i in seq(1:l))
  {
    
    cseg = cell_info$cell_bodies == i
    vcount <- table(cseg*vmask)
    vcount <- vcount[-1]
    #message(vcount)
    if( length(vcount) == 0)
    {
      empty_cells[i] = i
    }
  }
  
  empty_cells <- unlist(empty_cells)
  
  
  message(paste0("Number of empty cells: ", length(empty_cells)))


 
   #remove empty cells
  cell_bodies <- rmObjects(cell_info$cell_bodies, empty_cells)
  cell_bodies <- bwlabel(cell_bodies)
  
  FCCB <- computeFeatures(cell_bodies, ref = img[,,gfp_channel])
  
 
  membranes = cell_bodies - cell_inner
  
  FCM <- computeFeatures(membranes, ref = img[,,gfp_channel], xname = "membrane")
  FV <- computeFeatures(vmask, ref= img[,,gfp_channel], xname = "vac")
  message(paste0("Number of cells after empty cells removed: ", length(table(cell_bodies))))
  
  list(vacuoles = vmask, 
       membranes = membranes,
       FCM = FCM,
       #  FV = FV,
       FCCB = FCCB,
       cell_inner = cell_inner,
       cell_bodies = cell_bodies,
       FCCI = FCCI)
  
  
}
```






```{r}
remove_edge_membranes <-functions(membranes, FMM)
{
  contours <- ocontour(membranes)
  bound <- list(l = 3,
                  r = dim(channels$cmac)[1]-3,
                  t = 3,
                  b = dim(channels$cmac)[2]-3)
  # find more efficient way to do this
  left <- lapply(contours, function(x){min(x[,1])})
  right <- lapply(contours, function(x){max(x[,1])})
  top <- lapply(contours, function(x){min(x[,2])})
  bottom <- lapply(contours, function(x){max(x[,2])})
  removed <- c(which(left < bound$l),which(right > bound$r),  which(top < bound$t),which(bottom > bound$b))
  removed <- as.numeric(names(r))
  removed <- unique(removed) #line might be unecessary
  return(removed)

}
```

```{r}
roi_labels_demo <- function(m, FM) # generalize this later
{
  label_pts = FM[, c("m.cx", "m.cy")]
 labels <- as.numeric(names(table(m)[-1]))

  list(labels = labels, label_pts = label_pts)
}
```


```{r}
#FCB = computeFeatures.basic(cells$cell_bodies, ref = imggray[,,cmac_channel])
FMB = computeFeatures.moment(cells$cell_bodies, ref = imggray[,,gfp_channel], xnames = "membrane")
FMI = computeFeatures.moment(cells$cell_inner, ref = imggray[,,gfp_channel], xnames = "membrane")

#fh <- computeFeatures.haralick(c, ref = imggray[,,cmac_channel])
#fclosed <- computeFeatures.moment(c, ref = imggray[,,gfp_channel])
```



```{r}
p <- paintObjects(cells$membranes, tgt = channels$gfp, col = c("white", "white"))
pi <- paintObjects(cells$cell_inner, p, col = c('blue', 'blue'))
pp <- paintObjects(res$vacuoles, tgt = pi, col = c('yellow','yellow'))

#clabels <- roi_labels_demo(cells$cell_bodies, FMB, FMI)
blabels <- roi_labels_demo(cells$cell_bodies, FMB)
ilabels <- roi_labels_demo(cells$cell_inner, FMI)
show_labeled(blabels, ilabels, pp)
```

```{r}
show_labeled <- function(clabels, ilabels, timg)
{
  plot(timg)
   text(x = clabels$label_pts[,"m.cx"], 
         y =  clabels$label_pts[,"m.cy"], 
         labels = clabels$labels, 
         col = "red", 
         pos = c(2,3), 
         vfont = c("sans serif", "bold"))
     text(x = ilabels$label_pts[,"m.cx"], 
         y =  ilabels$label_pts[,"m.cy"], 
         labels = ilabels$labels, 
         col = "orange", 
         pos = c(2,3), 
         vfont = c("sans serif", "bold"))
}
```

```{r}
exclude_and_bind <- function(membranes, vacuoles,df)
{
  l = length(table(membranes))
  l = l-1
  
  fragments <- vector("list", l)
  empty_cells <- vector("list", l)
  
  for(i in seq(1:l))
  {
    seg <- membranes == i
    inner = fillHull(seg)
    if(all(seg == inner))
    {
     # print(paste0('hi ', i))#fragments[i] == i
      fragments[i] = as.numeric(i)
    }
    else
    {
      vcount <- table(inner*vacuoles)
      vcount <- vcount[-1] 
       if( length(vcount) == 0 )
      {
          # message(paste0(i, " ZERO VCOUNT"))
          empty_cells[i] = i
       }
      else
      {
        print(class(vcount))
        print(unname(vcount))
        df <- rbind(df, list(CellID = i,
                       vacuoles = list(-1000,-2000),
                       cell_area = -1000,
                       vac_area = -1000,
                       PM_vac_ratio = -1000,
                       cell_mpi = -1000,
                       vac_mpi = -1000))
      }
    }
  }
  return(df)
}
```

```{r}
f <- find_fragments(cells$cell_bodies)
```

```{r}
rmempty <- function(cell_info, vmask)
{
  
  l = length(table(cell_info$cell_bodies))
  l = l-1
  
  empty_cells <- vector("list", l)
  
  for(i in seq(1:l))
  {
    print(i)
    cseg = cell_info$cell_bodies == i
    cell_inner <- fillHull(cseg)
    vcount <- table(cell_inner*vmask)
    vcount <- vcount[-1]
    print(vcount)
    if( length(vcount) == 0 )
    {
      # message(paste0(i, " ZERO VCOUNT"))
      empty_cells[i] = i
    }
  }
  return(empty_cells)
}
```

```{r}
e <- rmempty(cells,res$vacuoles)
```


```{r}
remove_multiples <- function(cell_info, vmask, img)
{
  
  l = length(table(cell_info$cell_inner))
  l = l-1
  
  
  maxes <- vector("list", l)
  empty_cells <- vector("list", l)
  
  for(i in seq(1:l))
  {
    
    cseg = cell_info$cell_inner == i
    vcount <- table(cseg*vmask)
    vcount <- vcount[-1]
    #message(vcount)
    if( length(vcount) > 0)
    {
      
      v <- as.numeric(names(as.list(vcount)))
      # message(v)
      vcount <- unname(vcount)
      maxes[i] <- v[which(vcount == max(vcount))]
    }
    else
    {
      # message(paste0(i, " ZERO VCOUNT"))
      empty_cells[i] = i
    }
  }
  
  empty_cells <- unlist(empty_cells)
  
  
  message(paste0("Number of empty cells: ", length(empty_cells)))
  maxes <- unlist(maxes)
  extras <- which(!(seq(1:length(table(vmask)[-1])) %in% maxes))
  
  
  
  vmask <- rmObjects(vmask, extras)
  vmask <- bwlabel(vmask)
  
  
  # Not going to recompute features here for cell bodies/cell inner.  Can add that if needed but as of now it's not necessary and it will slow things down
  # recomputation of membrane features is needed, however
  
  
  
  #remove empty cells
  cell_inner <- rmObjects(cell_info$cell_inner, empty_cells)
  cell_inner <- bwlabel(cell_inner)
  #remove empty cells
  cell_bodies <- rmObjects(cell_info$cell_bodies, empty_cells)
  cell_bodies <- bwlabel(cell_bodies)
  FCCI <- computeFeatures(cell_inner, ref = img[,,gfp_channel])
  FCCB <- computeFeatures(cell_bodies, ref = img[,,gfp_channel])
  
  #remove empty membranes
  #membranes <- rmObjects(cell_info$membranes, empty_cells)
  # membranes <- bwlabel(membranes)
  membranes = cell_bodies - cell_inner
  
  FCM <- computeFeatures(membranes, ref = img[,,gfp_channel], xname = "membrane")
  FV <- computeFeatures(vmask, ref= img[,,gfp_channel], xname = "vac")
  message(paste0("Number of cells after empty cells removed: ", length(table(cell_bodies))))
  
  list(vacuoles = vmask, 
       membranes = membranes,
       FCM = FCM,
       #  FV = FV,
       FCCB = FCCB,
       cell_inner = cell_inner,
       cell_bodies = cell_bodies,
       FCCI = FCCI)
}
```
